pipeline {
    agent any

    environment {
        ALLURE_RESULTS = 'SauceDemoPOM/allure-results'
    }

    tools {
        maven 'maven'
        jdk 'JAVA_HOME'
    }

    stages {
        stage('Cloner dépôt') {
            steps {
                git 'https://github.com/mohamedmedini/SwagLab_Cucumber.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn -f SauceDemoPOM/pom.xml -Dtest=Runner clean verify'
            }
        }
    }

    post {
        always {
            // Publish test results even if tests fail
            junit 'SauceDemoPOM/target/surefire-reports/*.xml'
            
            // Generate Allure report always (pass or fail)
            allure([
                includeProperties: false,
                jdk: 'JAVA_HOME',
                results: [[path: "${env.ALLURE_RESULTS}"]],
                reportBuildPolicy: 'ALWAYS'
            ])
        }
    }
}
