name: Maven Cucumber Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'  # Cache Maven dependencies automatically

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-keyring.gpg
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Cucumber Tests
        run: mvn -Dtest=Runner verify
        working-directory: SauceDemoPOM

      - name: Generate Allure Report
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.17.1/allure-2.17.1.tgz
          tar -zxvf allure-2.17.1.tgz
          sudo mv allure-2.17.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

          # Check if results exist before generating
          if [ -d "SauceDemoPOM/target/allure-results" ]; then
            echo "Allure results found. Generating report..."
            allure generate SauceDemoPOM/target/allure-results --clean -o SauceDemoPOM/target/allure-report
          else
            echo "::warning:: No Allure results found. Skipping report generation."
            mkdir -p SauceDemoPOM/target/allure-report
            echo "<html><body><h2>No Allure results found</h2></body></html>" > SauceDemoPOM/target/allure-report/index.html
          fi

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: SauceDemoPOM/target/allure-report/



 
    


